[package]
name = "digestive"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
prost = "0.13.5"
reqwest = { version = "0.12.12" }
anyhow = "1.0.96"
log = "0.4.26"
env_logger = "0.11.6"
uuid = { version = "1.14.0", features = ["v4"] }

[build-dependencies]
tonic-build = "0.12.3"